name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@0.0.1
      with:
        # Docker Version
        docker_version: 19.03
        # Docker Channel
        docker_channel: stable
    - name: Start MongoDB As Docker
      uses: wbari/start-mongoDB@v0.2
      with:
        # MongoDB Version
        mongoDBVersion: 3.6
    - name: Build with Maven
      run: mvn clean install


      
