name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install MongoDB from docker
      run: docker pull mongo:4.0.4, docker run -d -p 27017-27019:27017-27019 --name mongodb mongo:4.0.4
    - name: Build with Maven
      run: mvn clean install


      
