name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup-java
      uses: olafurpg/setup-scala@v6
      with: 
        java-version: 1.11
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@0.0.1
      with:
        # Docker Version
        docker_version: 19.03
        # Docker Channel
        docker_channel: stable
    - name: Start MongoDB As Docker
      uses: wbari/start-mongoDB@v0.2
      with:
        # MongoDB Version
        mongoDBVersion: 3.6
    - name: Build with Maven
      run: mvn clean install
    - name: Comment Pull Request
      uses: thollander/actions-comment-pull-request@1.0.0
      with:
        # Message that should be printed in the pull request
        message: 'Github build message'
        # Github token of the repository (automatically created by Github)
        GITHUB_TOKEN: 586076608c93d0a7f223f6f7e0d097005649c891


      
